apiVersion: v1
kind: Service
metadata:
  name: hackathon
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hackathon

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: hello-kubernetes
          image: $ECR_URI:$BUILD_ID
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 2
            initialDelaySeconds: 15
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5